name: MD to HTML and Push
run-name: Generating HTML from Markdown (via ${{ github.actor }})
on:
  push:
    branches:
      - 'develop'
jobs:
  Generate-HTML:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Markdown-HTML (Generate HTML from MD)
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'
      - run: pip install markdown
      - run: python build.py
      - name: Git Auto Commit (Push all generated HTML)
        uses: stefanzweifel/git-auto-commit-action@v4.15.0
        with:
          commit_message: Generate new HTML
          create_branch: true
          branch: develop
          file_pattern: '*.html *.css *.js'
          push_options: '--force'
